PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), customer TEXT NOT NULL, phone_encrypted TEXT NOT NULL, garment TEXT NOT NULL, meters REAL NOT NULL, price REAL NOT NULL, quantity INTEGER NOT NULL, complexity TEXT NOT NULL, urgency INTEGER NOT NULL, fittings REAL NOT NULL, total REAL NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS materials(sku TEXT PRIMARY KEY,name TEXT NOT NULL,price REAL NOT NULL CHECK(price>0),stock REAL NOT NULL CHECK(stock>=0));
CREATE TABLE IF NOT EXISTS production(id INTEGER PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),customer TEXT NOT NULL,sku TEXT NOT NULL REFERENCES materials(sku),meters REAL NOT NULL CHECK(meters>0),quantity INTEGER NOT NULL CHECK(quantity>0),labor REAL NOT NULL CHECK(labor>=0),total REAL NOT NULL,status TEXT NOT NULL CHECK(status IN ('new','working','done')),created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),order_id INTEGER NOT NULL REFERENCES production(id) ON DELETE CASCADE,message TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS login_attempts(ip TEXT PRIMARY KEY,attempts INTEGER NOT NULL,last_time INTEGER NOT NULL);

