<?php
declare(strict_types=1);
require_once __DIR__.'/domain.php';
function data_dir(): string {$dir=getenv('LAB_DATA_DIR')?:dirname(__DIR__).'/data';if(!is_dir($dir))mkdir($dir,0700,true);return $dir;}
function db(): PDO {static $db;if(!$db){$db=new PDO('sqlite:'.data_dir().'/labs.sqlite');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);$db->exec('PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000');$db->exec(file_get_contents(dirname(__DIR__).'/database/schema.sql'));$db->exec("INSERT OR IGNORE INTO materials VALUES('COTTON','Бавовна',280,100),('LINEN','Льон',420,60),('WOOL','Вовна',650,35),('SILK','Шовк',850,15)");}return $db;}
function encryption_key(): string {$from=getenv('LAB_ENCRYPTION_KEY');if($from){$key=base64_decode($from,true);if($key===false||strlen($key)!==32)throw new RuntimeException('Invalid encryption key');return $key;}$file=data_dir().'/key.bin';if(!file_exists($file)){$handle=fopen($file,'x');if($handle){fwrite($handle,random_bytes(32));fclose($handle);chmod($file,0600);}}$key=file_get_contents($file);if(strlen($key)!==32)throw new RuntimeException('Invalid local key');return $key;}
function encrypt_phone(string $phone): string {$iv=random_bytes(12);$tag='';$cipher=openssl_encrypt($phone,'aes-256-gcm',encryption_key(),OPENSSL_RAW_DATA,$iv,$tag,'labs-phone-v1');if($cipher===false)throw new RuntimeException('Encryption failed');return base64_encode($iv.$tag.$cipher);}
function decrypt_phone(string $value): string {$raw=base64_decode($value,true);if($raw===false||strlen($raw)<28)throw new RuntimeException('Invalid ciphertext');$plain=openssl_decrypt(substr($raw,28),'aes-256-gcm',encryption_key(),OPENSSL_RAW_DATA,substr($raw,0,12),substr($raw,12,16),'labs-phone-v1');if($plain===false)throw new RuntimeException('Authentication failed');return $plain;}
function respond(array $data,int $status=200): never {http_response_code($status);echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);exit;}
function input_data(): array {if(strlen($_SERVER['CONTENT_TYPE']??'')===0||stripos($_SERVER['CONTENT_TYPE'],'application/json')!==0)respond(['message'=>'Потрібен JSON.'],415);$raw=file_get_contents('php://input',false,null,0,16385);if(strlen($raw)>16384)respond(['message'=>'Завеликий запит.'],413);try{$data=json_decode($raw,true,64,JSON_THROW_ON_ERROR);}catch(Throwable){respond(['message'=>'Некоректний JSON.'],400);}if(!is_array($data)||array_is_list($data))respond(['message'=>'Потрібен об’єкт JSON.'],400);return $data;}
function setup_session(): void {ini_set('session.use_strict_mode','1');$dir=data_dir().'/sessions';if(!is_dir($dir))mkdir($dir,0700,true);session_save_path($dir);session_name('LABSESSION');session_set_cookie_params(['httponly'=>true,'secure'=>getenv('LAB_HTTPS')==='1','samesite'=>'Lax','path'=>'/']);session_start();$_SESSION['csrf']??=bin2hex(random_bytes(32));}
function csrf(): void {$value=$_SERVER['HTTP_X_CSRF_TOKEN']??'';if(!is_string($value)||!hash_equals($_SESSION['csrf'],$value))respond(['message'=>'CSRF-токен відсутній або некоректний.'],403);}
function user_id(): int {if(empty($_SESSION['uid']))respond(['message'=>'Спочатку увійдіть через лабораторну №7.'],401);return (int)$_SESSION['uid'];}
function external_json(string $url): array {$context=stream_context_create(['http'=>['timeout'=>3,'ignore_errors'=>false,'header'=>"Accept: application/json\r\n"]]);$raw=@file_get_contents($url,false,$context,0,65537);if($raw===false||strlen($raw)>65536)throw new RuntimeException('API unavailable');$data=json_decode($raw,true,64,JSON_THROW_ON_ERROR);if(!is_array($data))throw new RuntimeException('Invalid API');return $data;}

