import test from 'node:test';import assert from 'node:assert/strict';import{spawn,spawnSync}from'node:child_process';import{mkdtemp,rm,readFile,readdir}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';import{randomUUID}from'node:crypto';import{fileURLToPath}from'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const php=process.env.PHP_BIN||'php',phpArgs=(process.env.PHP_ARGS||'').split('|').filter(Boolean);const base='http://127.0.0.1:8187';
test('PHP API integration and security',async t=>{
const data=await mkdtemp(path.join(tmpdir(),'web-labs-test-'));const env={...process.env,LAB_DATA_DIR:data,SENSOR_URL:'http://127.0.0.1:8191',SUPPLIER_URL:'http://127.0.0.1:8192',SENSOR_PORT:'8191',SUPPLIER_PORT:'8192'};const children=[];
function start(exe,args){const p=spawn(exe,args,{cwd:root,env,stdio:['ignore','ignore','pipe'],windowsHide:true});p.stderr.on('data',()=>{});children.push(p);return p;}
try{
start(process.execPath,['services/sensor-api.mjs']);start(process.execPath,['services/supplier-api.mjs']);start(php,[...phpArgs,'-S','127.0.0.1:8187','router.php']);
let ready=false;for(let i=0;i<60;i++){try{if((await fetch(base+'/api.php?resource=health')).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,100));}assert(ready,'API started');
const clients=[];function client(){const c={cookie:'',csrf:''};c.req=async(resource,method='GET',body,options={})=>{const headers={Cookie:c.cookie,...(body===undefined?{}:{'Content-Type':'application/json'}),...(method==='GET'||options.noCsrf?{}:{'X-CSRF-Token':c.csrf})};const res=await fetch(base+'/api.php?resource='+resource+(options.id?'&id='+options.id:''),{method,headers,body:body===undefined?undefined:JSON.stringify(body)});for(const value of res.headers.getSetCookie())c.cookie=value.split(';')[0];return{status:res.status,data:await res.json(),headers:res.headers};};c.session=async()=>{const r=await c.req('session');c.csrf=r.data.csrf;return r;};clients.push(c);return c;}
const a=client(),b=client();await a.session();await b.session();const password=randomUUID()+'!';
await t.test('PHP domain validation and cryptography assertions',()=>{const run=spawnSync(php,[...phpArgs,'tests/domain.php'],{cwd:root,env,encoding:'utf8',windowsHide:true});assert.equal(run.status,0,run.stderr);assert.match(run.stdout,/PHP assertions: 20 passed/);});
await t.test('Health and HTTP method contract',async()=>{assert.equal((await a.req('health')).data.ok,true);assert.equal((await a.req('health','POST',{})).status,405);});
await t.test('No unauthorized CRUD',async()=>assert.equal((await a.req('orders')).status,401));
await t.test('CSRF required even for registration',async()=>assert.equal((await a.req('auth','POST',{action:'register',email:'a@example.test',password},{noCsrf:true})).status,403));
for(const[c,email]of[[a,'a@example.test'],[b,'b@example.test']]){assert.equal((await c.req('auth','POST',{action:'register',email,password})).status,201);assert.equal((await c.req('auth','POST',{action:'login',email,password})).status,200);await c.session();}
await t.test('HttpOnly SameSite cookies and session rotation',async()=>{assert(a.cookie.startsWith('LABSESSION='));assert.equal((await a.session()).data.authenticated,true);});
await t.test('Sensor API has distinct changing samples',async()=>{const x=await a.req('sensors'),y=await a.req('sensors');assert.equal(x.status,200);assert(y.data.sequence>x.data.sequence);assert(Number.isFinite(y.data.distance));});
const order={customer:'<img src=x onerror=alert(1)>',phone:'+380000000000',garment:'dress',meters:2.5,price:280,quantity:1,fittings:120,complexity:'standard',urgency:0,total:.01};let id;
await t.test('Create with trusted server calculation',async()=>{const r=await a.req('orders','POST',order);assert.equal(r.status,201);id=r.data.id;assert.equal(r.data.cost.total,1720);});
await t.test('Read own data and safely retain text',async()=>{const row=(await a.req('orders')).data.items[0];assert.equal(row.customer,order.customer);assert.equal(row.phone,order.phone);assert.equal(row.total,1720);assert(!('phone_encrypted'in row));});
await t.test('Cross-user isolation and IDOR protection',async()=>{assert.equal((await b.req('orders')).data.items.length,0);assert.equal((await b.req('orders','PUT',order,{id})).status,404);assert.equal((await b.req('orders','DELETE',undefined,{id})).status,404);});
await t.test('Validation rejects invalid quantity and precision',async()=>{assert.equal((await a.req('orders','POST',{...order,quantity:1.5})).status,422);assert.equal((await a.req('orders','POST',{...order,meters:2.555})).status,422);});
await t.test('Update persists correctly',async()=>{const r=await a.req('orders','PUT',{...order,quantity:5},{id});assert.equal(r.status,200);assert.equal(r.data.cost.total,8170);assert.equal((await a.req('orders')).data.items[0].quantity,5);});
await t.test('SQL injection cannot bypass login',async()=>assert.equal((await b.req('auth','POST',{action:'login',email:"' OR 1=1 --",password})).status,422));
await t.test('CSRF attack refused',async()=>assert.equal((await a.req('orders','DELETE',undefined,{id,noCsrf:true})).status,403));
await t.test('Secrets are not publicly served',async()=>{for(const file of ['/data/labs.sqlite','/server/bootstrap.php','/database/schema.sql','/.env','/package-lock.json','/shared/../../database/schema.sql'])assert.equal((await fetch(base+file)).status,404,file);});
await t.test('Security response headers',async()=>{const r=await fetch(base+'/lab06/');assert.match(r.headers.get('content-security-policy'),/object-src 'none'/);assert.equal(r.headers.get('x-content-type-options'),'nosniff');});
await t.test('Passwords and phone encrypted at rest',async()=>{const bytes=await readFile(path.join(data,'labs.sqlite'));assert(!bytes.includes(Buffer.from(password)));assert(!bytes.includes(Buffer.from(order.phone)));assert(bytes.includes(Buffer.from('$2y$')));});
await t.test('Supplier sync and atomic stock reservation',async()=>{assert.equal((await a.req('materials','POST',{})).status,200);const before=(await a.req('materials')).data.items.find(x=>x.sku==='COTTON').stock;const r=await a.req('production','POST',{customer:'Навчальний клієнт',sku:'COTTON',meters:2.5,quantity:2,labor:900});assert.equal(r.status,201);assert.equal(r.data.total,3200);const pid=r.data.id;assert.equal((await a.req('materials')).data.items.find(x=>x.sku==='COTTON').stock,before-5);assert.equal((await b.req('production','PUT',{id:pid,status:'done'})).status,404);assert.equal((await a.req('production','PUT',{id:pid,status:'working'})).status,200);assert.equal((await a.req('notifications')).data.items.length,2);assert.equal((await b.req('notifications')).data.items.length,0);});
await t.test('Repeat sync preserves reserved stock',async()=>{const before=(await a.req('materials')).data.items.find(x=>x.sku==='COTTON').stock;await a.req('materials','POST',{});assert.equal((await a.req('materials')).data.items.find(x=>x.sku==='COTTON').stock,before);});
await t.test('Stock shortage rejected without changes',async()=>{const before=(await a.req('materials')).data.items;assert.equal((await a.req('production','POST',{customer:'Test',sku:'SILK',meters:20,quantity:100,labor:1})).status,422);assert.deepEqual((await a.req('materials')).data.items,before);});
await t.test('Verified SQLite backup includes key',async()=>{const r=spawnSync(php,[...phpArgs,'scripts/backup.php'],{cwd:root,env,encoding:'utf8',windowsHide:true});assert.equal(r.status,0,r.stderr);assert.equal(JSON.parse(r.stdout).integrity,'ok');const files=await readdir(path.join(data,'backups'));assert(files.some(f=>f.endsWith('.sqlite')));assert(files.some(f=>f.endsWith('.key')));});
await t.test('Delete and logout',async()=>{assert.equal((await a.req('orders','DELETE',undefined,{id})).status,200);assert.equal((await a.req('orders')).data.items.length,0);assert.equal((await a.req('auth','POST',{action:'logout'})).status,200);await a.session();assert.equal((await a.req('orders')).status,401);});
}finally{for(const p of children){p.kill();await new Promise(r=>{if(p.exitCode!==null||p.signalCode!==null)return r();p.once('exit',r);setTimeout(r,3000);});}await rm(data,{recursive:true,force:true});}
});
