import React,{useEffect,useRef,useState,useMemo} from 'react';
import{createRoot}from'react-dom/client';
import{HashRouter,Routes,Route,NavLink}from'react-router-dom';
import'../../shared/styles.css';import'./styles.css';
const sensors={distance:{label:'Відстань',unit:'см'},temperature:{label:'Температура',unit:'°C'},voltage:{label:'Напруга',unit:'В'}};
export function statistics(values){if(!values.length)return{min:0,max:0,mean:0};return{min:Math.min(...values),max:Math.max(...values),mean:values.reduce((s,v)=>s+v,0)/values.length};}
function Graph({samples,field}){const values=samples.map(s=>s[field]),stats=statistics(values),min=stats.min-1,max=stats.max+1;const points=values.map((v,i)=>[45+i*790/Math.max(values.length-1,1),240-(v-min)*200/(max-min)]);return <svg className="chart" viewBox="0 0 880 280" role="img" aria-label={'Графік: '+sensors[field].label}><rect width="880" height="280" fill="#f1f7f9"/>{[0,1,2,3,4].map(n=><g key={n}><line x1="45" y1={40+n*50} x2="835" y2={40+n*50} stroke="#d7e5eb"/><text x="4" y={45+n*50} fontSize="11" fill="#59727e">{(max-n*(max-min)/4).toFixed(1)}</text></g>)}<polyline fill="none" stroke="#2b8199" strokeWidth="3" points={points.map(p=>p.join(',')).join(' ')}/>{points.map(([x,y],i)=><circle key={i} cx={x} cy={y} r="3" fill="#b96532"/>)}<text x="45" y="266" fontSize="12" fill="#59727e">Останні {samples.length} вимірювань · {sensors[field].unit}</text></svg>;}
function Dashboard({samples,field,setField,running,setRunning,error}){const values=samples.map(s=>s[field]),stats=useMemo(()=>statistics(values),[samples,field]);return <><h1>Телеметрія робота</h1><p className="lead">Варіант 5 · аналіз даних і графік у реальному часі. Дані надходять через Fetch з окремого навчального API-симулятора.</p><div className="cards metrics">{[['Поточне',values.at(-1)||0],['Середнє',stats.mean],['Мінімум / максимум',stats.min.toFixed(2)+' / '+stats.max.toFixed(2)]].map(([label,value])=><div className="panel" key={label}><p className="small">{label}</p><div className="stat">{typeof value==='number'?value.toFixed(2):value}</div><small>{sensors[field].unit}</small></div>)}</div><section className="panel"><div className="graph-tools"><label className="field">Датчик<select value={field} onChange={e=>setField(e.target.value)}>{Object.entries(sensors).map(([key,s])=><option key={key} value={key}>{s.label}</option>)}</select></label><button onClick={()=>setRunning(v=>!v)}>{running?'Пауза':'Продовжити'}</button><span className="tag" role="status">{running?'Оновлення активне':'Призупинено'}</span></div><Graph samples={samples} field={field}/>{error&&<p role="alert" className="error">{error}</p>}<p className="small" data-testid="samples">Отримано точок: {samples.length}. {samples.at(-1)?.source}</p></section></>;}
function Settings({interval,setIntervalMs}){const [draft,setDraft]=useState(String(interval)),[message,setMessage]=useState('');return <section className="panel"><h1>Налаштування</h1><form onSubmit={e=>{e.preventDefault();const n=Number(draft);if(!Number.isInteger(n)||n<500||n>10000){setMessage('Вкажіть 500–10000 мс.');return;}setIntervalMs(n);setMessage('Інтервал оновлено.');}}><label className="field">Інтервал опитування, мс<input type="number" min="500" max="10000" value={draft} onChange={e=>setDraft(e.target.value)}/></label><button>Зберегти налаштування</button><p role="status">{message}</p></form><p className="small">Вікно графіка обмежено 30 точками. Запити, які ще виконуються, скасовуються при зміні налаштувань або виході.</p></section>;}
function App(){const[samples,setSamples]=useState([]),[field,setField]=useState('distance'),[running,setRunning]=useState(true),[interval,setIntervalMs]=useState(1000),[error,setError]=useState('');useEffect(()=>{if(!running)return;let stopped=false,timer;const controller=new AbortController();async function poll(){try{const response=await fetch('/api.php?resource=sensors',{signal:controller.signal,cache:'no-store'});if(!response.ok)throw Error('API недоступне. Запустіть sensor-api або перевірте сервер.');const row=await response.json();if(!Object.keys(sensors).every(k=>Number.isFinite(row[k])))throw Error('Некоректні значення API.');if(!stopped){setSamples(old=>[...old,row].slice(-30));setError('');}}catch(e){if(!stopped)setError(e.message);}finally{if(!stopped)timer=setTimeout(poll,interval);}}poll();return()=>{stopped=true;clearTimeout(timer);controller.abort();};},[running,interval]);return <><header><strong>05 / REACT · SENSOR LAB</strong><a href="/">Усі лабораторні ↗</a></header><main><nav className="react-nav"><NavLink to="/">Графік</NavLink><NavLink to="/settings">Налаштування</NavLink><NavLink to="/about">Про дані</NavLink></nav><Routes><Route path="/" element={<Dashboard {...{samples,field,setField,running,setRunning,error}}/>}/><Route path="/settings" element={<Settings {...{interval,setIntervalMs}}/>}/><Route path="/about" element={<section className="panel"><h1>Джерело телеметрії</h1><p>Власний Node.js API працює окремим процесом. PHP-проксі передає його JSON до React. Це симулятор трьох датчиків, не підключення до фізичного робота.</p><p>У застосунку є функціональні компоненти, стан форми useState, Fetch, useEffect з очищенням та React Router.</p></section>}/><Route path="*" element={<h1>Сторінку не знайдено</h1>}/></Routes></main><footer>Селіванов Назар · БЗІП-23</footer></>;}
createRoot(document.getElementById('root')).render(<HashRouter><App/></HashRouter>);

