import{api,refreshSession,textCell,money}from'/shared/api.mjs';
const form=document.querySelector('#order-form'),message=document.querySelector('#message');let editing=null,rows=[];
async function load(){try{rows=(await api('orders')).items;const body=document.querySelector('#orders');body.replaceChildren();for(const row of rows){const tr=document.createElement('tr');[row.id,row.customer,row.phone,row.quantity,money(row.total)].forEach(v=>textCell(tr,v));const cell=textCell(tr,'');const actions=document.createElement('div');actions.className='actions';for(const [label,action]of[['Редагувати','edit'],['Видалити','delete']]){const button=document.createElement('button');button.textContent=label;button.dataset.action=action;button.dataset.id=row.id;actions.append(button);}cell.append(actions);body.append(tr);}document.querySelector('#load-status').textContent=rows.length?'Записи прочитано з SQLite.':'Записів ще немає.';}catch(e){document.querySelector('#load-status').textContent=e.message;}}
function reset(){editing=null;form.reset();document.querySelector('#form-title').textContent='Нове замовлення';}
form.addEventListener('submit',async event=>{event.preventDefault();const d=Object.fromEntries(new FormData(form));for(const key of ['meters','price','quantity','fittings','urgency'])d[key]=Number(d[key]);const submit=form.querySelector('button');submit.disabled=true;try{const result=await api('orders',editing?'PUT':'POST',d,editing);message.textContent='Замовлення №'+result.id+' збережено в базі.';message.classList.remove('error');const cost=document.querySelector('#cost');cost.replaceChildren();for(const [key,label]of Object.entries({unit:'Один виріб',subtotal:'Партія',rush:'Терміновість',discount:'Знижка',total:'Разом'})){const p=document.createElement('p');p.textContent=label+': '+money(result.cost[key]);if(key==='total')p.className='stat';cost.append(p);}reset();await load();}catch(e){message.textContent=e.message;message.classList.add('error');}finally{submit.disabled=false;}});
document.querySelector('#cancel').addEventListener('click',reset);
document.querySelector('#orders').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const id=Number(b.dataset.id);if(b.dataset.action==='edit'){const row=rows.find(r=>r.id===id);for(const key of Object.keys(Object.fromEntries(new FormData(form))))form.elements[key].value=row[key];editing=id;document.querySelector('#form-title').textContent='Редагування №'+id;form.scrollIntoView();form.elements.customer.focus();}else if(confirm('Видалити замовлення №'+id+'?')){try{await api('orders','DELETE',undefined,id);if(editing===id)reset();await load();message.textContent='Замовлення видалено.';}catch(error){message.textContent=error.message;}}});
await refreshSession();await load();

